 FROM ubuntu:18.04

RUN apt-get update && apt-get install -y vim wget curl git

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.3.1-0-Linux-x86_64.sh -O ~/miniconda.sh
RUN bash ~/miniconda.sh -b -p /miniconda
ENV PATH="/miniconda/bin:$PATH"

# get env file seperately so it doesn't reinstall every time
RUN conda create -n commot -c conda-forge python==3.8 r-base==3.6.3 -y

ENV PATH="/usr/bin:/miniconda/envs/commot/bin:$PATH"
RUN which pip
RUN pip install --use-pep517 commot[tradeSeq]==0.0.3
RUN conda install -n commot -c r -c bioconda -c conda-forge r-lattice==0.20_38 r-locfit==1.5_9.4 r-mass==7.3_51.3 pygraphviz bioconductor-annotate==1.64.0 r-xml==3.99_0.3 bioconductor-summarizedexperiment==1.16.0 -y
RUN pip install jupyter tornado==6.1
RUN R -e 'install.packages("BiocManager", repos="http://cran.us.r-project.org")'
RUN R -e 'BiocManager::install("tradeSeq")'

COPY . /summer_researchers

CMD /bin/bash
